CREATE TABLE championship
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_championship PRIMARY KEY (id)
);

CREATE TABLE game
(
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    championship_id           INTEGER                                  NOT NULL,
    played_at                 TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    status_for_edition        VARCHAR(255)                             NOT NULL,
    scoreboard_image_name     VARCHAR(255),
    image_processing_status   VARCHAR(255),
    game_results_status       VARCHAR(255),
    game_results_accepted_by  INTEGER,
    game_results_input_method VARCHAR(255),
    CONSTRAINT pk_game PRIMARY KEY (id)
);

CREATE TABLE game_result
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id            INTEGER                                  NOT NULL,
    player_id          INTEGER,
    position           INTEGER,
    character_name     VARCHAR(255),
    score              INTEGER,
    max_score_achieved BOOLEAN,
    CONSTRAINT pk_gameresult PRIMARY KEY (id)
);

CREATE TABLE player
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        INTEGER                                  NOT NULL,
    character_name VARCHAR(255)                             NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_player PRIMARY KEY (id)
);

ALTER TABLE championship
    ADD CONSTRAINT uc_championship_name UNIQUE (name);

ALTER TABLE game_result
    ADD CONSTRAINT FK_GAMERESULT_ON_GAME FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE game_result
    ADD CONSTRAINT FK_GAMERESULT_ON_PLAYER FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_CHAMPIONSHIP FOREIGN KEY (championship_id) REFERENCES championship (id);