CREATE TABLE app_user
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                             NOT NULL,
    email    VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_appuser PRIMARY KEY (id)
);

ALTER TABLE player
    ADD CONSTRAINT FK_PLAYER_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL;

ALTER TABLE player
    ALTER COLUMN user_id DROP NOT NULL;